 BASIC OPERATIONS IN PANDAS SERIES
# CREATING a DATA FRAME IN THE PANDAS WITH SOME ROWS and COLUMNS - PERFORME THE BASIC FUNCTION

In [1]:
import numpy as np
import pandas as pd

In [7]:
df= pd.DataFrame({'Population':[34.34,46.45,33.45,87.78,24.5,234.65,878.67],
                  'GDP':[234345,3545456,43635764,5764686,431989864,796891,243456],
                
                  'Surface Area': [
        9984670,
        640679,
        357114,
        301336,
        377930,
        242495,
        9525067],
    'HDI': [
        0.913,
        0.888,
        0.916,
        0.873,
        0.891,
        0.907,
        0.915
    ],
    'Continent': [
        'America',
        'Europe',
        'Europe',
        'Europe',
        'Asia',
        'Europe',
        'America'
    ]})

In [8]:
df

   Population        GDP  Surface Area    HDI Continent
0       34.34     234345       9984670  0.913   America
1       46.45    3545456        640679  0.888    Europe
2       33.45   43635764        357114  0.916    Europe
3       87.78    5764686        301336  0.873    Europe
4       24.50  431989864        377930  0.891      Asia
5      234.65     796891        242495  0.907    Europe
6      878.67     243456       9525067  0.915   America

In [10]:
df.index = ['germany',
               'France',
                'Italy',
                'Spain',
                'Canada',
                'United Kingdom',
                'United States']

In [11]:
df

                Population        GDP  Surface Area    HDI Continent
germany              34.34     234345       9984670  0.913   America
France               46.45    3545456        640679  0.888    Europe
Italy                33.45   43635764        357114  0.916    Europe
Spain                87.78    5764686        301336  0.873    Europe
Canada               24.50  431989864        377930  0.891      Asia
United Kingdom      234.65     796891        242495  0.907    Europe
United States       878.67     243456       9525067  0.915   America

In [12]:
df.columns

Index(['Population', 'GDP', 'Surface Area', 'HDI', 'Continent'], dtype='object')

In [13]:
df.index

Index(['germany', 'France', 'Italy', 'Spain', 'Canada', 'United Kingdom',
       'United States'],
      dtype='object')

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, germany to United States
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Population    7 non-null      float64
 1   GDP           7 non-null      int64
 2   Surface Area  7 non-null      int64
 3   HDI           7 non-null      float64
 4   Continent     7 non-null      object
dtypes: float64(2), int64(2), object(1)
memory usage: 336.0+ bytes

In [18]:
df.dtypes

Population      float64
GDP               int64
Surface Area      int64
HDI             float64
Continent        object
dtype: object

In [20]:
df.describe()

       Population           GDP  Surface Area       HDI
count    7.000000  7.000000e+00  7.000000e+00  7.000000
mean   191.405714  6.945864e+07  3.061327e+06  0.900429
std    311.830584  1.606209e+08  4.576187e+06  0.016592
min     24.500000  2.343450e+05  2.424950e+05  0.873000
25%     33.895000  5.201735e+05  3.292250e+05  0.889500
50%     46.450000  3.545456e+06  3.779300e+05  0.907000
75%    161.215000  2.470022e+07  5.082873e+06  0.914000
max    878.670000  4.319899e+08  9.984670e+06  0.916000

In [22]:
df.shape

(7, 5)

In [23]:
df.size

35

In [24]:
#Individual columns in the DataFrame can be selected with regular indexing.

df['Population']

germany            34.34
France             46.45
Italy              33.45
Spain              87.78
Canada             24.50
United Kingdom    234.65
United States     878.67
Name: Population, dtype: float64

In [25]:
# DataFrame can be selected with iloc 

#in iloc ###number has to been useed inside the []
### gives horizontal data values 


df.iloc[2]

Population         33.45
GDP             43635764
Surface Area      357114
HDI                0.916
Continent         Europe
Name: Italy, dtype: object

In [26]:
# in loc ###aplahets has to been useed inside the []
## gives horizontal data values 


df.loc['germany']

Population        34.34
GDP              234345
Surface Area    9984670
HDI               0.913
Continent       America
Name: germany, dtype: object

In [33]:
df[['Population','Surface Area']]

                Population  Surface Area
germany              34.34       9984670
France               46.45        640679
Italy                33.45        357114
Spain                87.78        301336
Canada               24.50        377930
United Kingdom      234.65        242495
United States       878.67       9525067

In [34]:
df[1:3]

        Population       GDP  Surface Area    HDI Continent
France       46.45   3545456        640679  0.888    Europe
Italy        33.45  43635764        357114  0.916    Europe

In [39]:
df.iloc[0:4,3]

germany    0.913
France     0.888
Italy      0.916
Spain      0.873
Name: HDI, dtype: float64

In [41]:
df.loc['germany':'Canada','Surface Area']

germany    9984670
France      640679
Italy       357114
Spain       301336
Canada      377930
Name: Surface Area, dtype: int64