In [96]:
import pandas as pd

In [97]:
df= pd.read_excel(r'Customer Call List.xlsx')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [98]:
df.head

<bound method NDFrame.head of     CustomerID First_Name    Last_Name  Phone_Number  \
0         1001      Frodo      Baggins  123-545-5421
1         1002       Abed        Nadir  123/643/9775
2         1003     Walter       /White    7066950392
3         1004     Dwight      Schrute  123-543-2345
4         1005        Jon         Snow  876|678|3469
5         1006        Ron      Swanson  304-762-2467
6         1007       Jeff       Winger           NaN
7         1008   Sherlock       Holmes  876|678|3469
8         1009    Gandalf          NaN           N/a
9         1010      Peter       Parker  123-545-5421
10        1011    Samwise       Gamgee           NaN
11        1012      Harry    ...Potter    7066950392
12        1013        Don       Draper  123-543-2345
13        1014     Leslie        Knope  876|678|3469
14        1015       Toby  Flenderson_  304-762-2467
15        1016        Ron      Weasley  123-545-5421
16        1017   Michael         Scott  123/643/9775
17        1018      Clark         Kent    7066950392
18        1019      Creed       Braton           N/a
19        1020     Anakin    Skywalker  876|678|3469
20        1020     Anakin    Skywalker  876|678|3469

                                  Address Paying Customer Do_Not_Contact  \
0                   123 Shire Lane, Shire             Yes             No
1                     93 West Main Street              No            Yes
2                      298 Drugs Driveway               N            NaN
3   980 Paper Avenue, Pennsylvania, 18503             Yes              Y
4                        123 Dragons Road               Y             No
5                        768 City Parkway             Yes            Yes
6                       1209 South Street              No             No
7                           98 Clue Drive               N             No
8                        123 Middle Earth             Yes            NaN
9              25th Main Street, New York             Yes             No
10                  612 Shire Lane, Shire             Yes             No
11                   2394 Hogwarts Avenue               Y            NaN
12                       2039 Main Street             Yes              N
13                       343 City Parkway             Yes             No
14                          214 HR Avenue               N             No
15                   2395 Hogwarts Avenue              No              N
16         121 Paper Avenue, Pennsylvania             Yes             No
17                        3498 Super Lane               Y            NaN
18                                    N/a             N/a            Yes
19            910 Tatooine Road, Tatooine             Yes              N
20            910 Tatooine Road, Tatooine             Yes              N

    Not_Useful_Column
0                True
1               False
2                True
3                True
4                True
5                True
6               False
7               False
8               False
9                True
10               True
11               True
12              False
13              False
14              False
15              False
16              False
17               True
18               True
19               True
20               True  >

In [99]:
df=df.drop_duplicates()
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [100]:
# drop not needed columns 
df=df.drop(columns='Not_Useful_Column')

In [101]:
print(df)

    CustomerID First_Name    Last_Name  Phone_Number  \
0         1001      Frodo      Baggins  123-545-5421
1         1002       Abed        Nadir  123/643/9775
2         1003     Walter       /White    7066950392
3         1004     Dwight      Schrute  123-543-2345
4         1005        Jon         Snow  876|678|3469
5         1006        Ron      Swanson  304-762-2467
6         1007       Jeff       Winger           NaN
7         1008   Sherlock       Holmes  876|678|3469
8         1009    Gandalf          NaN           N/a
9         1010      Peter       Parker  123-545-5421
10        1011    Samwise       Gamgee           NaN
11        1012      Harry    ...Potter    7066950392
12        1013        Don       Draper  123-543-2345
13        1014     Leslie        Knope  876|678|3469
14        1015       Toby  Flenderson_  304-762-2467
15        1016        Ron      Weasley  123-545-5421
16        1017   Michael         Scott  123/643/9775
17        1018      Clark         Kent    7066950392
18        1019      Creed       Braton           N/a
19        1020     Anakin    Skywalker  876|678|3469

                                  Address Paying Customer Do_Not_Contact
0                   123 Shire Lane, Shire             Yes             No
1                     93 West Main Street              No            Yes
2                      298 Drugs Driveway               N            NaN
3   980 Paper Avenue, Pennsylvania, 18503             Yes              Y
4                        123 Dragons Road               Y             No
5                        768 City Parkway             Yes            Yes
6                       1209 South Street              No             No
7                           98 Clue Drive               N             No
8                        123 Middle Earth             Yes            NaN
9              25th Main Street, New York             Yes             No
10                  612 Shire Lane, Shire             Yes             No
11                   2394 Hogwarts Avenue               Y            NaN
12                       2039 Main Street             Yes              N
13                       343 City Parkway             Yes             No
14                          214 HR Avenue               N             No
15                   2395 Hogwarts Avenue              No              N
16         121 Paper Avenue, Pennsylvania             Yes             No
17                        3498 Super Lane               Y            NaN
18                                    N/a             N/a            Yes
19            910 Tatooine Road, Tatooine             Yes              N

In [102]:
# we are going to remove the extra strings like ...,/, _ from the columns last name 
# going to use strip () rather than replace (). 
#in strip we can use left lstrip(), right rstrip() and  can use normal strip('/._123') use to remove everything at once

df['Last_Name']=df['Last_Name'].str.lstrip('/')
df['Last_Name']=df['Last_Name'].str.lstrip('...')
df['Last_Name']=df['Last_Name'].str.rstrip('_')

#can use normal strip('/._123') use to remove everything at once

#df['Last_Name']=df['Last_Name'].str.strip('/.123_')
print(df)

    CustomerID First_Name   Last_Name  Phone_Number  \
0         1001      Frodo     Baggins  123-545-5421
1         1002       Abed       Nadir  123/643/9775
2         1003     Walter       White    7066950392
3         1004     Dwight     Schrute  123-543-2345
4         1005        Jon        Snow  876|678|3469
5         1006        Ron     Swanson  304-762-2467
6         1007       Jeff      Winger           NaN
7         1008   Sherlock      Holmes  876|678|3469
8         1009    Gandalf         NaN           N/a
9         1010      Peter      Parker  123-545-5421
10        1011    Samwise      Gamgee           NaN
11        1012      Harry      Potter    7066950392
12        1013        Don      Draper  123-543-2345
13        1014     Leslie       Knope  876|678|3469
14        1015       Toby  Flenderson  304-762-2467
15        1016        Ron     Weasley  123-545-5421
16        1017   Michael        Scott  123/643/9775
17        1018      Clark        Kent    7066950392
18        1019      Creed      Braton           N/a
19        1020     Anakin   Skywalker  876|678|3469

                                  Address Paying Customer Do_Not_Contact
0                   123 Shire Lane, Shire             Yes             No
1                     93 West Main Street              No            Yes
2                      298 Drugs Driveway               N            NaN
3   980 Paper Avenue, Pennsylvania, 18503             Yes              Y
4                        123 Dragons Road               Y             No
5                        768 City Parkway             Yes            Yes
6                       1209 South Street              No             No
7                           98 Clue Drive               N             No
8                        123 Middle Earth             Yes            NaN
9              25th Main Street, New York             Yes             No
10                  612 Shire Lane, Shire             Yes             No
11                   2394 Hogwarts Avenue               Y            NaN
12                       2039 Main Street             Yes              N
13                       343 City Parkway             Yes             No
14                          214 HR Avenue               N             No
15                   2395 Hogwarts Avenue              No              N
16         121 Paper Avenue, Pennsylvania             Yes             No
17                        3498 Super Lane               Y            NaN
18                                    N/a             N/a            Yes
19            910 Tatooine Road, Tatooine             Yes              N

In [103]:
# cleaning the phone number
#inbetween the phone number we have  _/| etc.
# lambda function can take any number of arguments, but can only have one expression

help('lambda')

Lambdas
*******

   lambda_expr ::= "lambda" [parameter_list] ":" expression

Lambda expressions (sometimes called lambda forms) are used to create
anonymous functions. The expression "lambda parameters: expression"
yields a function object.  The unnamed object behaves like a function
object defined with:

   def <lambda>(parameters):
       return expression

See section Function definitions for the syntax of parameter lists.
Note that functions created with lambda expressions cannot contain
statements or annotations.

Related help topics: FUNCTIONS

In [104]:
#use replace funnction to remove the any -|/ inbetween the numbers
# we are giving 0:3 because we need - after 3 numbers
df['Phone_Number']=df['Phone_Number'].str.replace('[^a-zA-Z0-9]','', regex = True)
print(df)

    CustomerID First_Name   Last_Name Phone_Number  \
0         1001      Frodo     Baggins   1235455421
1         1002       Abed       Nadir   1236439775
2         1003     Walter       White          NaN
3         1004     Dwight     Schrute   1235432345
4         1005        Jon        Snow   8766783469
5         1006        Ron     Swanson   3047622467
6         1007       Jeff      Winger          NaN
7         1008   Sherlock      Holmes   8766783469
8         1009    Gandalf         NaN           Na
9         1010      Peter      Parker   1235455421
10        1011    Samwise      Gamgee          NaN
11        1012      Harry      Potter          NaN
12        1013        Don      Draper   1235432345
13        1014     Leslie       Knope   8766783469
14        1015       Toby  Flenderson   3047622467
15        1016        Ron     Weasley   1235455421
16        1017   Michael        Scott   1236439775
17        1018      Clark        Kent          NaN
18        1019      Creed      Braton           Na
19        1020     Anakin   Skywalker   8766783469

                                  Address Paying Customer Do_Not_Contact
0                   123 Shire Lane, Shire             Yes             No
1                     93 West Main Street              No            Yes
2                      298 Drugs Driveway               N            NaN
3   980 Paper Avenue, Pennsylvania, 18503             Yes              Y
4                        123 Dragons Road               Y             No
5                        768 City Parkway             Yes            Yes
6                       1209 South Street              No             No
7                           98 Clue Drive               N             No
8                        123 Middle Earth             Yes            NaN
9              25th Main Street, New York             Yes             No
10                  612 Shire Lane, Shire             Yes             No
11                   2394 Hogwarts Avenue               Y            NaN
12                       2039 Main Street             Yes              N
13                       343 City Parkway             Yes             No
14                          214 HR Avenue               N             No
15                   2395 Hogwarts Avenue              No              N
16         121 Paper Avenue, Pennsylvania             Yes             No
17                        3498 Super Lane               Y            NaN
18                                    N/a             N/a            Yes
19            910 Tatooine Road, Tatooine             Yes              N

In [105]:
df['Phone_Number']=df['Phone_Number'].apply(lambda x:str(x))
df['Phone_Number']=df['Phone_Number'].apply(lambda x: x[0:3] + '-' + x[3:6] + '-' + x[6:10])
df['Phone_Number']

0     123-545-5421
1     123-643-9775
2            nan--
3     123-543-2345
4     876-678-3469
5     304-762-2467
6            nan--
7     876-678-3469
8             Na--
9     123-545-5421
10           nan--
11           nan--
12    123-543-2345
13    876-678-3469
14    304-762-2467
15    123-545-5421
16    123-643-9775
17           nan--
18            Na--
19    876-678-3469
Name: Phone_Number, dtype: object

In [106]:
print(df)

    CustomerID First_Name   Last_Name  Phone_Number  \
0         1001      Frodo     Baggins  123-545-5421
1         1002       Abed       Nadir  123-643-9775
2         1003     Walter       White         nan--
3         1004     Dwight     Schrute  123-543-2345
4         1005        Jon        Snow  876-678-3469
5         1006        Ron     Swanson  304-762-2467
6         1007       Jeff      Winger         nan--
7         1008   Sherlock      Holmes  876-678-3469
8         1009    Gandalf         NaN          Na--
9         1010      Peter      Parker  123-545-5421
10        1011    Samwise      Gamgee         nan--
11        1012      Harry      Potter         nan--
12        1013        Don      Draper  123-543-2345
13        1014     Leslie       Knope  876-678-3469
14        1015       Toby  Flenderson  304-762-2467
15        1016        Ron     Weasley  123-545-5421
16        1017   Michael        Scott  123-643-9775
17        1018      Clark        Kent         nan--
18        1019      Creed      Braton          Na--
19        1020     Anakin   Skywalker  876-678-3469

                                  Address Paying Customer Do_Not_Contact
0                   123 Shire Lane, Shire             Yes             No
1                     93 West Main Street              No            Yes
2                      298 Drugs Driveway               N            NaN
3   980 Paper Avenue, Pennsylvania, 18503             Yes              Y
4                        123 Dragons Road               Y             No
5                        768 City Parkway             Yes            Yes
6                       1209 South Street              No             No
7                           98 Clue Drive               N             No
8                        123 Middle Earth             Yes            NaN
9              25th Main Street, New York             Yes             No
10                  612 Shire Lane, Shire             Yes             No
11                   2394 Hogwarts Avenue               Y            NaN
12                       2039 Main Street             Yes              N
13                       343 City Parkway             Yes             No
14                          214 HR Avenue               N             No
15                   2395 Hogwarts Avenue              No              N
16         121 Paper Avenue, Pennsylvania             Yes             No
17                        3498 Super Lane               Y            NaN
18                                    N/a             N/a            Yes
19            910 Tatooine Road, Tatooine             Yes              N

In [107]:
# we are splitting the address based on zipcode, house number_streetname , state
# the orginal dataset already had comma inbetween these zipcode, house number_streetname , state so sing the comma we are going to seperate it 

df['Address'].str.split(',',n=2,expand=True)

                       0              1       2
0         123 Shire Lane          Shire    None
1    93 West Main Street           None    None
2     298 Drugs Driveway           None    None
3       980 Paper Avenue   Pennsylvania   18503
4       123 Dragons Road           None    None
5       768 City Parkway           None    None
6      1209 South Street           None    None
7          98 Clue Drive           None    None
8       123 Middle Earth           None    None
9       25th Main Street       New York    None
10        612 Shire Lane          Shire    None
11  2394 Hogwarts Avenue           None    None
12      2039 Main Street           None    None
13      343 City Parkway           None    None
14         214 HR Avenue           None    None
15  2395 Hogwarts Avenue           None    None
16      121 Paper Avenue   Pennsylvania    None
17       3498 Super Lane           None    None
18                   N/a           None    None
19     910 Tatooine Road       Tatooine    None

In [108]:
df[['house_number_street_name','state','Zip_code']]=df['Address'].str.split(',',n=2,expand=True)
print(df)

    CustomerID First_Name   Last_Name  Phone_Number  \
0         1001      Frodo     Baggins  123-545-5421
1         1002       Abed       Nadir  123-643-9775
2         1003     Walter       White         nan--
3         1004     Dwight     Schrute  123-543-2345
4         1005        Jon        Snow  876-678-3469
5         1006        Ron     Swanson  304-762-2467
6         1007       Jeff      Winger         nan--
7         1008   Sherlock      Holmes  876-678-3469
8         1009    Gandalf         NaN          Na--
9         1010      Peter      Parker  123-545-5421
10        1011    Samwise      Gamgee         nan--
11        1012      Harry      Potter         nan--
12        1013        Don      Draper  123-543-2345
13        1014     Leslie       Knope  876-678-3469
14        1015       Toby  Flenderson  304-762-2467
15        1016        Ron     Weasley  123-545-5421
16        1017   Michael        Scott  123-643-9775
17        1018      Clark        Kent         nan--
18        1019      Creed      Braton          Na--
19        1020     Anakin   Skywalker  876-678-3469

                                  Address Paying Customer Do_Not_Contact  \
0                   123 Shire Lane, Shire             Yes             No
1                     93 West Main Street              No            Yes
2                      298 Drugs Driveway               N            NaN
3   980 Paper Avenue, Pennsylvania, 18503             Yes              Y
4                        123 Dragons Road               Y             No
5                        768 City Parkway             Yes            Yes
6                       1209 South Street              No             No
7                           98 Clue Drive               N             No
8                        123 Middle Earth             Yes            NaN
9              25th Main Street, New York             Yes             No
10                  612 Shire Lane, Shire             Yes             No
11                   2394 Hogwarts Avenue               Y            NaN
12                       2039 Main Street             Yes              N
13                       343 City Parkway             Yes             No
14                          214 HR Avenue               N             No
15                   2395 Hogwarts Avenue              No              N
16         121 Paper Avenue, Pennsylvania             Yes             No
17                        3498 Super Lane               Y            NaN
18                                    N/a             N/a            Yes
19            910 Tatooine Road, Tatooine             Yes              N

   house_number_street_name          state Zip_code
0            123 Shire Lane          Shire     None
1       93 West Main Street           None     None
2        298 Drugs Driveway           None     None
3          980 Paper Avenue   Pennsylvania    18503
4          123 Dragons Road           None     None
5          768 City Parkway           None     None
6         1209 South Street           None     None
7             98 Clue Drive           None     None
8          123 Middle Earth           None     None
9          25th Main Street       New York     None
10           612 Shire Lane          Shire     None
11     2394 Hogwarts Avenue           None     None
12         2039 Main Street           None     None
13         343 City Parkway           None     None
14            214 HR Avenue           None     None
15     2395 Hogwarts Avenue           None     None
16         121 Paper Avenue   Pennsylvania     None
17          3498 Super Lane           None     None
18                      N/a           None     None
19        910 Tatooine Road       Tatooine     None

In [109]:
df['Do_Not_Contact']=df['Do_Not_Contact'].str.replace('Yes','Y')
df['Do_Not_Contact']=df['Do_Not_Contact'].str.replace('No','N')
print(df)

    CustomerID First_Name   Last_Name  Phone_Number  \
0         1001      Frodo     Baggins  123-545-5421
1         1002       Abed       Nadir  123-643-9775
2         1003     Walter       White         nan--
3         1004     Dwight     Schrute  123-543-2345
4         1005        Jon        Snow  876-678-3469
5         1006        Ron     Swanson  304-762-2467
6         1007       Jeff      Winger         nan--
7         1008   Sherlock      Holmes  876-678-3469
8         1009    Gandalf         NaN          Na--
9         1010      Peter      Parker  123-545-5421
10        1011    Samwise      Gamgee         nan--
11        1012      Harry      Potter         nan--
12        1013        Don      Draper  123-543-2345
13        1014     Leslie       Knope  876-678-3469
14        1015       Toby  Flenderson  304-762-2467
15        1016        Ron     Weasley  123-545-5421
16        1017   Michael        Scott  123-643-9775
17        1018      Clark        Kent         nan--
18        1019      Creed      Braton          Na--
19        1020     Anakin   Skywalker  876-678-3469

                                  Address Paying Customer Do_Not_Contact  \
0                   123 Shire Lane, Shire             Yes              N
1                     93 West Main Street              No              Y
2                      298 Drugs Driveway               N            NaN
3   980 Paper Avenue, Pennsylvania, 18503             Yes              Y
4                        123 Dragons Road               Y              N
5                        768 City Parkway             Yes              Y
6                       1209 South Street              No              N
7                           98 Clue Drive               N              N
8                        123 Middle Earth             Yes            NaN
9              25th Main Street, New York             Yes              N
10                  612 Shire Lane, Shire             Yes              N
11                   2394 Hogwarts Avenue               Y            NaN
12                       2039 Main Street             Yes              N
13                       343 City Parkway             Yes              N
14                          214 HR Avenue               N              N
15                   2395 Hogwarts Avenue              No              N
16         121 Paper Avenue, Pennsylvania             Yes              N
17                        3498 Super Lane               Y            NaN
18                                    N/a             N/a              Y
19            910 Tatooine Road, Tatooine             Yes              N

   house_number_street_name          state Zip_code
0            123 Shire Lane          Shire     None
1       93 West Main Street           None     None
2        298 Drugs Driveway           None     None
3          980 Paper Avenue   Pennsylvania    18503
4          123 Dragons Road           None     None
5          768 City Parkway           None     None
6         1209 South Street           None     None
7             98 Clue Drive           None     None
8          123 Middle Earth           None     None
9          25th Main Street       New York     None
10           612 Shire Lane          Shire     None
11     2394 Hogwarts Avenue           None     None
12         2039 Main Street           None     None
13         343 City Parkway           None     None
14            214 HR Avenue           None     None
15     2395 Hogwarts Avenue           None     None
16         121 Paper Avenue   Pennsylvania     None
17          3498 Super Lane           None     None
18                      N/a           None     None
19        910 Tatooine Road       Tatooine     None

In [110]:
df['Paying Customer']=df['Paying Customer'].str.replace('Yes','Y')
df['Paying Customer']=df['Paying Customer'].str.replace('No','N')
print(df)

    CustomerID First_Name   Last_Name  Phone_Number  \
0         1001      Frodo     Baggins  123-545-5421
1         1002       Abed       Nadir  123-643-9775
2         1003     Walter       White         nan--
3         1004     Dwight     Schrute  123-543-2345
4         1005        Jon        Snow  876-678-3469
5         1006        Ron     Swanson  304-762-2467
6         1007       Jeff      Winger         nan--
7         1008   Sherlock      Holmes  876-678-3469
8         1009    Gandalf         NaN          Na--
9         1010      Peter      Parker  123-545-5421
10        1011    Samwise      Gamgee         nan--
11        1012      Harry      Potter         nan--
12        1013        Don      Draper  123-543-2345
13        1014     Leslie       Knope  876-678-3469
14        1015       Toby  Flenderson  304-762-2467
15        1016        Ron     Weasley  123-545-5421
16        1017   Michael        Scott  123-643-9775
17        1018      Clark        Kent         nan--
18        1019      Creed      Braton          Na--
19        1020     Anakin   Skywalker  876-678-3469

                                  Address Paying Customer Do_Not_Contact  \
0                   123 Shire Lane, Shire               Y              N
1                     93 West Main Street               N              Y
2                      298 Drugs Driveway               N            NaN
3   980 Paper Avenue, Pennsylvania, 18503               Y              Y
4                        123 Dragons Road               Y              N
5                        768 City Parkway               Y              Y
6                       1209 South Street               N              N
7                           98 Clue Drive               N              N
8                        123 Middle Earth               Y            NaN
9              25th Main Street, New York               Y              N
10                  612 Shire Lane, Shire               Y              N
11                   2394 Hogwarts Avenue               Y            NaN
12                       2039 Main Street               Y              N
13                       343 City Parkway               Y              N
14                          214 HR Avenue               N              N
15                   2395 Hogwarts Avenue               N              N
16         121 Paper Avenue, Pennsylvania               Y              N
17                        3498 Super Lane               Y            NaN
18                                    N/a             N/a              Y
19            910 Tatooine Road, Tatooine               Y              N

   house_number_street_name          state Zip_code
0            123 Shire Lane          Shire     None
1       93 West Main Street           None     None
2        298 Drugs Driveway           None     None
3          980 Paper Avenue   Pennsylvania    18503
4          123 Dragons Road           None     None
5          768 City Parkway           None     None
6         1209 South Street           None     None
7             98 Clue Drive           None     None
8          123 Middle Earth           None     None
9          25th Main Street       New York     None
10           612 Shire Lane          Shire     None
11     2394 Hogwarts Avenue           None     None
12         2039 Main Street           None     None
13         343 City Parkway           None     None
14            214 HR Avenue           None     None
15     2395 Hogwarts Avenue           None     None
16         121 Paper Avenue   Pennsylvania     None
17          3498 Super Lane           None     None
18                      N/a           None     None
19        910 Tatooine Road       Tatooine     None

In [111]:

df=df.fillna('')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,house_number_street_name,state,Zip_code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,Y,93 West Main Street,,
2,1003,Walter,White,nan--,298 Drugs Driveway,N,,298 Drugs Driveway,,
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,,
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,768 City Parkway,,
6,1007,Jeff,Winger,nan--,1209 South Street,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,,
8,1009,Gandalf,,Na--,123 Middle Earth,Y,,123 Middle Earth,,
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,nan--,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,
11,1012,Harry,Potter,nan--,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,nan--,3498 Super Lane,Y,,3498 Super Lane,,
18,1019,Creed,Braton,Na--,N/a,N/a,Y,N/a,,
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

In [112]:
# Keep only the rows where Do_Not_Contact is NOT equal to Y
df = df[df["Do_Not_Contact"] != 'Y']
print(df)

#or
 # for x in df.index:   
#Go through each row one by one."
#    if df.loc[x, "Do_Not_Contact"] == 'Y':
#
  #      df.drop(x, inplace=True)
#Make the change directly in the original DataFrame."

#Without inplace=True, Pandas would create a new DataFrame and leave the original unchanged.

    CustomerID First_Name   Last_Name  Phone_Number  \
0         1001      Frodo     Baggins  123-545-5421
2         1003     Walter       White         nan--
4         1005        Jon        Snow  876-678-3469
6         1007       Jeff      Winger         nan--
7         1008   Sherlock      Holmes  876-678-3469
8         1009    Gandalf                      Na--
9         1010      Peter      Parker  123-545-5421
10        1011    Samwise      Gamgee         nan--
11        1012      Harry      Potter         nan--
12        1013        Don      Draper  123-543-2345
13        1014     Leslie       Knope  876-678-3469
14        1015       Toby  Flenderson  304-762-2467
15        1016        Ron     Weasley  123-545-5421
16        1017   Michael        Scott  123-643-9775
17        1018      Clark        Kent         nan--
19        1020     Anakin   Skywalker  876-678-3469

                           Address Paying Customer Do_Not_Contact  \
0            123 Shire Lane, Shire               Y              N
2               298 Drugs Driveway               N
4                 123 Dragons Road               Y              N
6                1209 South Street               N              N
7                    98 Clue Drive               N              N
8                 123 Middle Earth               Y
9       25th Main Street, New York               Y              N
10           612 Shire Lane, Shire               Y              N
11            2394 Hogwarts Avenue               Y
12                2039 Main Street               Y              N
13                343 City Parkway               Y              N
14                   214 HR Avenue               N              N
15            2395 Hogwarts Avenue               N              N
16  121 Paper Avenue, Pennsylvania               Y              N
17                 3498 Super Lane               Y
19     910 Tatooine Road, Tatooine               Y              N

   house_number_street_name          state Zip_code
0            123 Shire Lane          Shire
2        298 Drugs Driveway
4          123 Dragons Road
6         1209 South Street
7             98 Clue Drive
8          123 Middle Earth
9          25th Main Street       New York
10           612 Shire Lane          Shire
11     2394 Hogwarts Avenue
12         2039 Main Street
13         343 City Parkway
14            214 HR Avenue
15     2395 Hogwarts Avenue
16         121 Paper Avenue   Pennsylvania
17          3498 Super Lane
19        910 Tatooine Road       Tatooine

In [117]:

df = df[df["Phone_Number"] != 'nan--']
print(df)

    CustomerID First_Name   Last_Name  Phone_Number  \
0         1001      Frodo     Baggins  123-545-5421
4         1005        Jon        Snow  876-678-3469
7         1008   Sherlock      Holmes  876-678-3469
8         1009    Gandalf                      Na--
9         1010      Peter      Parker  123-545-5421
12        1013        Don      Draper  123-543-2345
13        1014     Leslie       Knope  876-678-3469
14        1015       Toby  Flenderson  304-762-2467
15        1016        Ron     Weasley  123-545-5421
16        1017   Michael        Scott  123-643-9775
19        1020     Anakin   Skywalker  876-678-3469

                           Address Paying Customer Do_Not_Contact  \
0            123 Shire Lane, Shire               Y              N
4                 123 Dragons Road               Y              N
7                    98 Clue Drive               N              N
8                 123 Middle Earth               Y
9       25th Main Street, New York               Y              N
12                2039 Main Street               Y              N
13                343 City Parkway               Y              N
14                   214 HR Avenue               N              N
15            2395 Hogwarts Avenue               N              N
16  121 Paper Avenue, Pennsylvania               Y              N
19     910 Tatooine Road, Tatooine               Y              N

   house_number_street_name          state Zip_code
0            123 Shire Lane          Shire
4          123 Dragons Road
7             98 Clue Drive
8          123 Middle Earth
9          25th Main Street       New York
12         2039 Main Street
13         343 City Parkway
14            214 HR Avenue
15     2395 Hogwarts Avenue
16         121 Paper Avenue   Pennsylvania
19        910 Tatooine Road       Tatooine

In [119]:
# now to reset the index
# to have proper order from 1 ,2,3,...
df=df.reset_index(drop=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,house_number_street_name,state,Zip_code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
1,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,,
2,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,,
3,1009,Gandalf,,Na--,123 Middle Earth,Y,,123 Middle Earth,,
4,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,
5,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,,
6,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,,
7,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,,
8,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
9,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
10,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,