In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('Driver.csv')
df.head()

   Driver ID First Name Last Name        Birthdate
0     992648   Pasquale      Hake   8/12/1983 0:00
1     913487      Becky   Gregori  20/10/1990 0:00
2     787584    Doretta    Bortle  13/03/1987 0:00
3     744618      Wally    Duncan  12/09/1987 0:00
4     657404   Marylynn    Hunger  20/01/1985 0:00

In [6]:
df2=pd.read_csv('License.csv')
df2.head()

   Driver ID License Type  Test Passed  Points
0     108704          Car            2       5
1     787584          Car            1       5
2     177070          Car            1       8
3     391232          Car            2       7
4     744618          Car            2      12

In [7]:
df['Full_name']=df['First Name'] +' '+ df['Last Name']
print(df['Full_name'])
print(df)

0        Pasquale Hake
1        Becky Gregori
2       Doretta Bortle
3         Wally Duncan
4      Marylynn Hunger
5       Ngan Klingbeil
6        Luna Lundgren
7          Shawnta Hix
8          Rubin Debus
9         Kaley Newnam
10        Ami Follette
11         Lynn Rarick
12        Karyl Fallin
13       Dexter Shawgo
14      Karole Sturman
15        Gianna Patao
16    Kathyrn Hilliard
17    Kathyrn Hilliard
18    Kathyrn Hilliard
19        Otis Lamborn
20        Elsa Brisbin
Name: Full_name, dtype: object
    Driver ID First Name  Last Name        Birthdate         Full_name
0      992648   Pasquale       Hake   8/12/1983 0:00     Pasquale Hake
1      913487      Becky    Gregori  20/10/1990 0:00     Becky Gregori
2      787584    Doretta     Bortle  13/03/1987 0:00    Doretta Bortle
3      744618      Wally     Duncan  12/09/1987 0:00      Wally Duncan
4      657404   Marylynn     Hunger  20/01/1985 0:00   Marylynn Hunger
5      611421       Ngan  Klingbeil   7/04/1995 0:00    Ngan Klingbeil
6      610285       Luna   Lundgren  24/10/1985 0:00     Luna Lundgren
7      549988    Shawnta        Hix  28/09/1983 0:00       Shawnta Hix
8      489839      Rubin      Debus  24/09/1984 0:00       Rubin Debus
9      391232      Kaley     Newnam  14/12/1987 0:00      Kaley Newnam
10     364215        Ami   Follette  19/02/1978 0:00      Ami Follette
11     344641       Lynn     Rarick  28/07/2003 0:00       Lynn Rarick
12     322449      Karyl     Fallin   7/12/1984 0:00      Karyl Fallin
13     309078     Dexter     Shawgo  24/12/1974 0:00     Dexter Shawgo
14     302033     Karole    Sturman  26/04/2004 0:00    Karole Sturman
15     177070     Gianna      Patao  16/09/1978 0:00      Gianna Patao
16     108704    Kathyrn   Hilliard   5/10/1979 0:00  Kathyrn Hilliard
17     108704    Kathyrn   Hilliard   5/10/1979 0:00  Kathyrn Hilliard
18      99999    Kathyrn   Hilliard  12/05/1998 0:00  Kathyrn Hilliard
19      46584       Otis    Lamborn  20/12/1984 0:00      Otis Lamborn
20      20021       Elsa    Brisbin   3/02/2005 0:00      Elsa Brisbin

In [11]:
#remove the time from the birthdate column
df['Birthdate']=pd.to_datetime(df['Birthdate'],dayfirst=True)
print(df['Birthdate'])

0    1983-12-08
1    1990-10-20
2    1987-03-13
3    1987-09-12
4    1985-01-20
5    1995-04-07
6    1985-10-24
7    1983-09-28
8    1984-09-24
9    1987-12-14
10   1978-02-19
11   2003-07-28
12   1984-12-07
13   1974-12-24
14   2004-04-26
15   1978-09-16
16   1979-10-05
17   1979-10-05
18   1998-05-12
19   1984-12-20
20   2005-02-03
Name: Birthdate, dtype: datetime64[ns]

In [19]:
df=df.sort_values(by=['First Name','Last Name'],ascending=True)
print(df)

    Driver ID First Name  Last Name  Birthdate         Full_name
10     364215        Ami   Follette 1978-02-19      Ami Follette
1      913487      Becky    Gregori 1990-10-20     Becky Gregori
13     309078     Dexter     Shawgo 1974-12-24     Dexter Shawgo
2      787584    Doretta     Bortle 1987-03-13    Doretta Bortle
20      20021       Elsa    Brisbin 2005-02-03      Elsa Brisbin
15     177070     Gianna      Patao 1978-09-16      Gianna Patao
9      391232      Kaley     Newnam 1987-12-14      Kaley Newnam
14     302033     Karole    Sturman 2004-04-26    Karole Sturman
12     322449      Karyl     Fallin 1984-12-07      Karyl Fallin
16     108704    Kathyrn   Hilliard 1979-10-05  Kathyrn Hilliard
17     108704    Kathyrn   Hilliard 1979-10-05  Kathyrn Hilliard
18      99999    Kathyrn   Hilliard 1998-05-12  Kathyrn Hilliard
6      610285       Luna   Lundgren 1985-10-24     Luna Lundgren
11     344641       Lynn     Rarick 2003-07-28       Lynn Rarick
4      657404   Marylynn     Hunger 1985-01-20   Marylynn Hunger
5      611421       Ngan  Klingbeil 1995-04-07    Ngan Klingbeil
19      46584       Otis    Lamborn 1984-12-20      Otis Lamborn
0      992648   Pasquale       Hake 1983-12-08     Pasquale Hake
8      489839      Rubin      Debus 1984-09-24       Rubin Debus
7      549988    Shawnta        Hix 1983-09-28       Shawnta Hix
3      744618      Wally     Duncan 1987-09-12      Wally Duncan

In [15]:
# df.sort_values(by=['First Name'],ascending=True)

    Driver ID First Name  Last Name  Birthdate         Full_name
10     364215        Ami   Follette 1978-02-19      Ami Follette
1      913487      Becky    Gregori 1990-10-20     Becky Gregori
13     309078     Dexter     Shawgo 1974-12-24     Dexter Shawgo
2      787584    Doretta     Bortle 1987-03-13    Doretta Bortle
20      20021       Elsa    Brisbin 2005-02-03      Elsa Brisbin
15     177070     Gianna      Patao 1978-09-16      Gianna Patao
9      391232      Kaley     Newnam 1987-12-14      Kaley Newnam
14     302033     Karole    Sturman 2004-04-26    Karole Sturman
12     322449      Karyl     Fallin 1984-12-07      Karyl Fallin
16     108704    Kathyrn   Hilliard 1979-10-05  Kathyrn Hilliard
17     108704    Kathyrn   Hilliard 1979-10-05  Kathyrn Hilliard
18      99999    Kathyrn   Hilliard 1998-05-12  Kathyrn Hilliard
6      610285       Luna   Lundgren 1985-10-24     Luna Lundgren
11     344641       Lynn     Rarick 2003-07-28       Lynn Rarick
4      657404   Marylynn     Hunger 1985-01-20   Marylynn Hunger
5      611421       Ngan  Klingbeil 1995-04-07    Ngan Klingbeil
19      46584       Otis    Lamborn 1984-12-20      Otis Lamborn
0      992648   Pasquale       Hake 1983-12-08     Pasquale Hake
8      489839      Rubin      Debus 1984-09-24       Rubin Debus
7      549988    Shawnta        Hix 1983-09-28       Shawnta Hix
3      744618      Wally     Duncan 1987-09-12      Wally Duncan

In [27]:
#Remove the duplicates method 1
df=df.drop_duplicates()
print(df)

    Driver ID First Name  Last Name  Birthdate         Full_name
10     364215        Ami   Follette 1978-02-19      Ami Follette
1      913487      Becky    Gregori 1990-10-20     Becky Gregori
13     309078     Dexter     Shawgo 1974-12-24     Dexter Shawgo
2      787584    Doretta     Bortle 1987-03-13    Doretta Bortle
20      20021       Elsa    Brisbin 2005-02-03      Elsa Brisbin
15     177070     Gianna      Patao 1978-09-16      Gianna Patao
9      391232      Kaley     Newnam 1987-12-14      Kaley Newnam
14     302033     Karole    Sturman 2004-04-26    Karole Sturman
12     322449      Karyl     Fallin 1984-12-07      Karyl Fallin
16     108704    Kathyrn   Hilliard 1979-10-05  Kathyrn Hilliard
18      99999    Kathyrn   Hilliard 1998-05-12  Kathyrn Hilliard
6      610285       Luna   Lundgren 1985-10-24     Luna Lundgren
11     344641       Lynn     Rarick 2003-07-28       Lynn Rarick
4      657404   Marylynn     Hunger 1985-01-20   Marylynn Hunger
5      611421       Ngan  Klingbeil 1995-04-07    Ngan Klingbeil
19      46584       Otis    Lamborn 1984-12-20      Otis Lamborn
0      992648   Pasquale       Hake 1983-12-08     Pasquale Hake
8      489839      Rubin      Debus 1984-09-24       Rubin Debus
7      549988    Shawnta        Hix 1983-09-28       Shawnta Hix
3      744618      Wally     Duncan 1987-09-12      Wally Duncan

In [26]:
# 16	108704	Kathyrn	Hilliard	1979-10-05	Kathyrn Hilliard
# 18	99999	Kathyrn	Hilliard	1998-05-12	Kathyrn Hilliard
# here we have 2 person with same name with different id 
# here we are checking duplicates based on first name and last name 

df.drop_duplicates(subset=['First Name'	,'Last Name'])

    Driver ID First Name  Last Name  Birthdate         Full_name
10     364215        Ami   Follette 1978-02-19      Ami Follette
1      913487      Becky    Gregori 1990-10-20     Becky Gregori
13     309078     Dexter     Shawgo 1974-12-24     Dexter Shawgo
2      787584    Doretta     Bortle 1987-03-13    Doretta Bortle
20      20021       Elsa    Brisbin 2005-02-03      Elsa Brisbin
15     177070     Gianna      Patao 1978-09-16      Gianna Patao
9      391232      Kaley     Newnam 1987-12-14      Kaley Newnam
14     302033     Karole    Sturman 2004-04-26    Karole Sturman
12     322449      Karyl     Fallin 1984-12-07      Karyl Fallin
16     108704    Kathyrn   Hilliard 1979-10-05  Kathyrn Hilliard
6      610285       Luna   Lundgren 1985-10-24     Luna Lundgren
11     344641       Lynn     Rarick 2003-07-28       Lynn Rarick
4      657404   Marylynn     Hunger 1985-01-20   Marylynn Hunger
5      611421       Ngan  Klingbeil 1995-04-07    Ngan Klingbeil
19      46584       Otis    Lamborn 1984-12-20      Otis Lamborn
0      992648   Pasquale       Hake 1983-12-08     Pasquale Hake
8      489839      Rubin      Debus 1984-09-24       Rubin Debus
7      549988    Shawnta        Hix 1983-09-28       Shawnta Hix
3      744618      Wally     Duncan 1987-09-12      Wally Duncan

In [42]:
#merge the data frame dataset 1, dataset2 and try to merge it using different joining methods like right, left,inner 
df=pd.merge(df,df2,left_on='Driver ID',right_on='Driver ID',how='left')
print(df)
df.head(3)

    Driver ID First Name  Last Name  Birthdate         Full_name  \
0      364215        Ami   Follette 1978-02-19      Ami Follette
1      913487      Becky    Gregori 1990-10-20     Becky Gregori
2      309078     Dexter     Shawgo 1974-12-24     Dexter Shawgo
3      787584    Doretta     Bortle 1987-03-13    Doretta Bortle
4       20021       Elsa    Brisbin 2005-02-03      Elsa Brisbin
5      177070     Gianna      Patao 1978-09-16      Gianna Patao
6      391232      Kaley     Newnam 1987-12-14      Kaley Newnam
7      302033     Karole    Sturman 2004-04-26    Karole Sturman
8      322449      Karyl     Fallin 1984-12-07      Karyl Fallin
9      108704    Kathyrn   Hilliard 1979-10-05  Kathyrn Hilliard
10      99999    Kathyrn   Hilliard 1998-05-12  Kathyrn Hilliard
11     610285       Luna   Lundgren 1985-10-24     Luna Lundgren
12     344641       Lynn     Rarick 2003-07-28       Lynn Rarick
13     657404   Marylynn     Hunger 1985-01-20   Marylynn Hunger
14     611421       Ngan  Klingbeil 1995-04-07    Ngan Klingbeil
15      46584       Otis    Lamborn 1984-12-20      Otis Lamborn
16     992648   Pasquale       Hake 1983-12-08     Pasquale Hake
17     489839      Rubin      Debus 1984-09-24       Rubin Debus
18     549988    Shawnta        Hix 1983-09-28       Shawnta Hix
19     744618      Wally     Duncan 1987-09-12      Wally Duncan

   License Type_x  Test Passed_x  Points_x License Type_y  Test Passed_y  \
0      Motorcycle            2.0       6.0     Motorcycle            2.0
1             Car            1.0       7.0            Car            1.0
2      Motorcycle            2.0      11.0     Motorcycle            2.0
3             Car            1.0       5.0            Car            1.0
4      Motorcycle            2.0       4.0     Motorcycle            2.0
5             Car            1.0       8.0            Car            1.0
6             Car            2.0       7.0            Car            2.0
7      Motorcycle            2.0       4.0     Motorcycle            2.0
8      Motorcycle            2.0      12.0     Motorcycle            2.0
9             Car            2.0       5.0            Car            2.0
10            NaN            NaN       NaN            NaN            NaN
11            Car            2.0       5.0            Car            2.0
12            Car            2.0       5.0            Car            2.0
13     Motorcycle            2.0       7.0     Motorcycle            2.0
14     Motorcycle            1.0       3.0     Motorcycle            1.0
15            Car            2.0      11.0            Car            2.0
16            Car            1.0      12.0            Car            1.0
17     Motorcycle            1.0       6.0     Motorcycle            1.0
18            Car            1.0       6.0            Car            1.0
19            Car            2.0      12.0            Car            2.0

    Points_y TTest Passed_y License Type  Test Passed  Points
0        6.0             no   Motorcycle          2.0     6.0
1        7.0            1.0          Car          1.0     7.0
2       11.0             no   Motorcycle          2.0    11.0
3        5.0            1.0          Car          1.0     5.0
4        4.0             no   Motorcycle          2.0     4.0
5        8.0            1.0          Car          1.0     8.0
6        7.0             no          Car          2.0     7.0
7        4.0             no   Motorcycle          2.0     4.0
8       12.0             no   Motorcycle          2.0    12.0
9        5.0             no          Car          2.0     5.0
10       NaN            NaN          NaN          NaN     NaN
11       5.0             no          Car          2.0     5.0
12       5.0             no          Car          2.0     5.0
13       7.0             no   Motorcycle          2.0     7.0
14       3.0            1.0   Motorcycle          1.0     3.0
15      11.0             no          Car          2.0    11.0
16      12.0            1.0          Car          1.0    12.0
17       6.0            1.0   Motorcycle          1.0     6.0
18       6.0            1.0          Car          1.0     6.0
19      12.0             no          Car          2.0    12.0

,Driver ID,First Name,Last Name,Birthdate,Full_name,License Type_x,Test Passed_x,Points_x,License Type_y,Test Passed_y,Points_y,TTest Passed_y,License Type,Test Passed,Points
0,364215,Ami,Follette,1978-02-19,Ami Follette,Motorcycle,2.0,6.0,Motorcycle,2.0,6.0,no,Motorcycle,2.0,6.0
1,913487,Becky,Gregori,1990-10-20,Becky Gregori,Car,1.0,7.0,Car,1.0,7.0,1.0,Car,1.0,7.0
2,309078,Dexter,Shawgo,1974-12-24,Dexter Shawgo,Motorcycle,2.0,11.0,Motorcycle,2.0,11.0,no,Motorcycle,2.0,11.0

In [32]:
pd.merge(df,df2,left_on='Driver ID',right_on='Driver ID',how='inner')

,Driver ID,First Name,Last Name,Birthdate,Full_name,License Type,Test Passed,Points
0,364215,Ami,Follette,1978-02-19,Ami Follette,Motorcycle,2,6
1,913487,Becky,Gregori,1990-10-20,Becky Gregori,Car,1,7
2,309078,Dexter,Shawgo,1974-12-24,Dexter Shawgo,Motorcycle,2,11
3,787584,Doretta,Bortle,1987-03-13,Doretta Bortle,Car,1,5
4,20021,Elsa,Brisbin,2005-02-03,Elsa Brisbin,Motorcycle,2,4
5,177070,Gianna,Patao,1978-09-16,Gianna Patao,Car,1,8
6,391232,Kaley,Newnam,1987-12-14,Kaley Newnam,Car,2,7
7,302033,Karole,Sturman,2004-04-26,Karole Sturman,Motorcycle,2,4
8,322449,Karyl,Fallin,1984-12-07,Karyl Fallin,Motorcycle,2,12
9,108704,Kathyrn,Hilliard,1979-10-05,Kathyrn Hilliard,Car,2,5
10,610285,Luna,Lundgren,1985-10-24,Luna Lundgren,Car,2,5
11,344641,Lynn,Rarick,2003-07-28,Lynn Rarick,Car,2,5
12,657404,Marylynn,Hunger,1985-01-20,Marylynn Hunger,Motorcycle,2,7
13,611421,Ngan,Klingbeil,1995-04-07,Ngan Klingbeil,Motorcycle,1,3
14,46584,Otis,Lamborn,1984-12-20,Otis Lamborn,Car,2,11
15,992648,Pasquale,Hake,1983-12-08,Pasquale Hake,Car,1,12
16,489839,Rubin,Debus,1984-09-24,Rubin Debus,Motorcycle,1,6
17,549988,Shawnta,Hix,1983-09-28,Shawnta Hix,Car,1,6
18,744618,Wally,Duncan,1987-09-12,Wally Duncan,Car,2,12

In [33]:
pd.merge(df,df2,left_on='Driver ID',right_on='Driver ID',how='right')

,Driver ID,First Name,Last Name,Birthdate,Full_name,License Type,Test Passed,Points
0,108704,Kathyrn,Hilliard,1979-10-05,Kathyrn Hilliard,Car,2,5
1,787584,Doretta,Bortle,1987-03-13,Doretta Bortle,Car,1,5
2,177070,Gianna,Patao,1978-09-16,Gianna Patao,Car,1,8
3,391232,Kaley,Newnam,1987-12-14,Kaley Newnam,Car,2,7
4,744618,Wally,Duncan,1987-09-12,Wally Duncan,Car,2,12
5,913487,Becky,Gregori,1990-10-20,Becky Gregori,Car,1,7
6,610285,Luna,Lundgren,1985-10-24,Luna Lundgren,Car,2,5
7,46584,Otis,Lamborn,1984-12-20,Otis Lamborn,Car,2,11
8,344641,Lynn,Rarick,2003-07-28,Lynn Rarick,Car,2,5
9,549988,Shawnta,Hix,1983-09-28,Shawnta Hix,Car,1,6
10,992648,Pasquale,Hake,1983-12-08,Pasquale Hake,Car,1,12
11,302033,Karole,Sturman,2004-04-26,Karole Sturman,Motorcycle,2,4
12,322449,Karyl,Fallin,1984-12-07,Karyl Fallin,Motorcycle,2,12
13,20021,Elsa,Brisbin,2005-02-03,Elsa Brisbin,Motorcycle,2,4
14,309078,Dexter,Shawgo,1974-12-24,Dexter Shawgo,Motorcycle,2,11
15,611421,Ngan,Klingbeil,1995-04-07,Ngan Klingbeil,Motorcycle,1,3
16,489839,Rubin,Debus,1984-09-24,Rubin Debus,Motorcycle,1,6
17,364215,Ami,Follette,1978-02-19,Ami Follette,Motorcycle,2,6
18,657404,Marylynn,Hunger,1985-01-20,Marylynn Hunger,Motorcycle,2,7

In [41]:
#replace the test passed 1 and 2 with yes and no
df['TTest Passed_y']=df['Test Passed_y'].replace(1.0,'yes')
df['TTest Passed_y']=df['Test Passed_y'].replace(2.0,'no')
df

,Driver ID,First Name,Last Name,Birthdate,Full_name,License Type_x,Test Passed_x,Points_x,License Type_y,Test Passed_y,Points_y,TTest Passed_y
0,364215,Ami,Follette,1978-02-19,Ami Follette,Motorcycle,2.0,6.0,Motorcycle,2.0,6.0,no
1,913487,Becky,Gregori,1990-10-20,Becky Gregori,Car,1.0,7.0,Car,1.0,7.0,1.0
2,309078,Dexter,Shawgo,1974-12-24,Dexter Shawgo,Motorcycle,2.0,11.0,Motorcycle,2.0,11.0,no
3,787584,Doretta,Bortle,1987-03-13,Doretta Bortle,Car,1.0,5.0,Car,1.0,5.0,1.0
4,20021,Elsa,Brisbin,2005-02-03,Elsa Brisbin,Motorcycle,2.0,4.0,Motorcycle,2.0,4.0,no
5,177070,Gianna,Patao,1978-09-16,Gianna Patao,Car,1.0,8.0,Car,1.0,8.0,1.0
6,391232,Kaley,Newnam,1987-12-14,Kaley Newnam,Car,2.0,7.0,Car,2.0,7.0,no
7,302033,Karole,Sturman,2004-04-26,Karole Sturman,Motorcycle,2.0,4.0,Motorcycle,2.0,4.0,no
8,322449,Karyl,Fallin,1984-12-07,Karyl Fallin,Motorcycle,2.0,12.0,Motorcycle,2.0,12.0,no
9,108704,Kathyrn,Hilliard,1979-10-05,Kathyrn Hilliard,Car,2.0,5.0,Car,2.0,5.0,no
10,99999,Kathyrn,Hilliard,1998-05-12,Kathyrn Hilliard,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,610285,Luna,Lundgren,1985-10-24,Luna Lundgren,Car,2.0,5.0,Car,2.0,5.0,no
12,344641,Lynn,Rarick,2003-07-28,Lynn Rarick,Car,2.0,5.0,Car,2.0,5.0,no
13,657404,Marylynn,Hunger,1985-01-20,Marylynn Hunger,Motorcycle,2.0,7.0,Motorcycle,2.0,7.0,no
14,611421,Ngan,Klingbeil,1995-04-07,Ngan Klingbeil,Motorcycle,1.0,3.0,Motorcycle,1.0,3.0,1.0
15,46584,Otis,Lamborn,1984-12-20,Otis Lamborn,Car,2.0,11.0,Car,2.0,11.0,no
16,992648,Pasquale,Hake,1983-12-08,Pasquale Hake,Car,1.0,12.0,Car,1.0,12.0,1.0
17,489839,Rubin,Debus,1984-09-24,Rubin Debus,Motorcycle,1.0,6.0,Motorcycle,1.0,6.0,1.0
18,549988,Shawnta,Hix,1983-09-28,Shawnta Hix,Car,1.0,6.0,Car,1.0,6.0,1.0
19,744618,Wally,Duncan,1987-09-12,Wally Duncan,Car,2.0,12.0,Car,2.0,12.0,no